name: Build
on: 
  pull_request:
    paths-ignore: 
      - '**.md'
      - 'LICENSE'
      - 'prototype/**'
  push:
    paths-ignore: 
      - '**.md'
      - 'LICENSE'
      - 'prototype/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Nwlink
        run: |
          npm install -g nwlink
          echo "$HOME/.npm-global/bin" >> $GITHUB_PATH

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly    
          target: thumbv7em-none-eabihf

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Prepare for building
        run: mkdir -p target/nwa
        
      - name: Build app
        run: just build

      - name: Move to target/nwa
        run: mv target/thumbv7em-none-eabihf/release/nw_3d_grapher target/nwa/nw_3d_grapher.nwa
      
      - name: Build app (obj)
        run: just build o
      
      - name: Move to target/nwa (obj)
        run: mv target/thumbv7em-none-eabihf/release/nw_3d_grapher target/nwa/nw_3d_grapher_obj.nwa

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nw_3d_grapher_nwas
          path: target/nwa/*
        