name: Build
on: 
  pull_request:
    paths: 
      - 'src/**'
      - '.github/workflows/*'
      - 'Makefile'
  push:
    paths: 
      - 'src/**'
      - '.github/workflows/*'
      - 'Makefile'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
        
      - name: Build
        run: make
      - name: Upload build artifacts
        uses: actions-rs/cargo@v1
        with:
          command: build