name: Build
on: 
  pull_request:
    paths-ignore: 
      - '**.md'
      - 'LICENSE'
      - 'prototype/**'
  push:
    paths-ignore: 
      - '**.md'
      - 'LICENSE'
      - 'prototype/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly    
          target: thumbv7em-none-eabihf

      - name: Install just
        uses: extractions/setup-just@v3
        
      - name: Build app
        run: just build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nw-3d-grapher
          path: target/**/NW3DGrapher
        